n = int(input())
if n == 0:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print("")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
if n == 1:
    print("")
    print("      *")
    print("      *")
    print("      *")
    print("")
    print("      *")
    print("      *")
    print("      *")
    print("")
if n == 2:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
if n == 3:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
if n == 4:
    print("")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print("")
if n == 5:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
if n == 6:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
if n == 7:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print("")
    print("      *")
    print("      *")
    print("      *")
    print("")
if n == 8:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
if n == 9:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
